### ISSUE TITLE
Angular 17 / Composable Storefront 2211.19 compatibility

### ISSUE THREAD

**Issue by stormpanda** [e-Spirit/fs-spartacus-bridge#1]
Hello,

I am currently working on the upgrade to Composable Storefront 2211.19. We are using the Spartacus Bridge, but it seems like it is not compatible with the new version anymore. 

The issue that I face is that when trying to run the application I get the following error:

`./node_modules/fs-spartacus-bridge/node_modules/@angular/common/fesm2020/common.mjs:2950:12-32 - Error: export 'ɵɵInputFlags' (imported as 'i0') was not found in '@angular/core'`

This is probably a result of Angular 15 and 17 clashing as `ɵɵInputFlags` is internal API.

I see that you are still using Angular 15 (as CSF was before the latest update). Are there any plans to update the library?

**Comment by mko-cp** [comment]
Hi @stormpanda,

thanks for letting us know. We will perform an update and will let you know once the new version is available.

**Comment by ecom-espirit** [comment]
Hi @stormpanda,
the new version is now available. You can find the releasenotes here:
https://docs.e-spirit.com/ecom/fsconnect-sap-headless/24.5.0/FS_Connect_SAP_hl_Releasenotes_EN.html

**Comment by hsc-cp** [comment]
Hi @stormpanda,
the new version is now available. You can find the releasenotes here:
https://docs.e-spirit.com/ecom/fsconnect-sap-headless/24.5.0/FS_Connect_SAP_hl_Releasenotes_EN.html

**Comment by stormpanda** [comment]
Perfect, thanks for letting me know! I will start doing the Angular Update first thing next week. Have a nice weekend!
